[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/caicloud/nirvana"

[[constraint]]
  name = "github.com/elastic/beats"
  version = "6.5.4"

[[constraint]]
  name = "github.com/elastic/go-ucfg"
  version = "0.5.1"

[[constraint]]
  name = "gopkg.in/fsnotify/fsnotify.v1"
  version = "1.4.7"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "github.com/caicloud/clientset"
  branch = "release-1.14"
